package com.orm;

/**
 * TOrder generated by MyEclipse Persistence Tools
 */

public class Tshouhuo implements java.io.Serializable
{

	// Fields

	private int id;

	private String name;

	private String tel;

	private String youbian;
	
	private String adr;  
	
	private String user_id;

	// Constructors

	/** default constructor */
	public Tshouhuo()
	{
	}

	public int getId() {
		return id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getTel() {
		return tel;
	}

	public void setTel(String tel) {
		this.tel = tel;
	}

	public String getYoubian() {
		return youbian;
	}

	public void setYoubian(String youbian) {
		this.youbian = youbian;
	}

	public String getAdr() {
		return adr;
	}

	public void setAdr(String adr) {
		this.adr = adr;
	}

	public String getUser_id() {
		return user_id;
	}

	public void setUser_id(String userId) {
		user_id = userId;
	}

    
	
}